=== aparra/appia/config/xml/appiaxml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT appia (template*,management?,channel*)>
<!ATTLIST appia
	multischedulers (yes|no) #IMPLIED
	scheduler CDATA #IMPLIED
	threadFactory CDATA #IMPLIED>
<!ELEMENT template (session+)>
<!ATTLIST template 
	name CDATA #REQUIRED>
<!ELEMENT session (protocol)>
<!ATTLIST session 
	name CDATA #REQUIRED 
	sharing (private|label|global) #REQUIRED>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT management EMPTY>
<!ATTLIST management
	naming_host CDATA #IMPLIED
	naming_port CDATA #IMPLIED
	local (yes|no) #IMPLIED>
<!ELEMENT channel (memorymanagement?,chsession*)>
<!ATTLIST channel
	name CDATA #REQUIRED
	template CDATA #REQUIRED
	initialized (yes|no) #REQUIRED
	managed (yes|no) #IMPLIED
	label CDATA #IMPLIED
	messageFactory CDATA #IMPLIED>
<!ELEMENT chsession (parameter*)>
<!ATTLIST chsession
	name CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED>
<!ELEMENT memorymanagement EMPTY>
<!ATTLIST memorymanagement
	size CDATA #REQUIRED
	up_threshold CDATA #REQUIRED
	down_threshold CDATA #REQUIRED>

=== aparra/appia/config/jgcs/open_group/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
         "http://appia.di.fc.ul.pt/xml/3.2/appiaxml.dtd">

<appia>

<template name="tcp">
	<session name="TCPSession" sharing="private">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="remoteview" sharing="private">
		<protocol>net.sf.appia.protocols.group.remote.RemoteViewLayer</protocol>
	</session>
	<session name="remoteaddr" sharing="private">
		<protocol>net.sf.appia.jgcs.protocols.remote.RemoteAddressLayer</protocol>
	</session>
	<session name="atsl" sharing="private">
		<protocol>net.sf.appia.jgcs.protocols.top.SimpleTOPLayer</protocol>
	</session>
</template>

<channel name="rrpc" template="tcp" initialized="no">
	<memorymanagement size="40000000" up_threshold="15000000" down_threshold="7000000" />
	<chsession name="remoteview">
		<parameter name="gossip">10.10.0.2:10000</parameter>
	</chsession>
	<chsession name="remoteaddr">
		<parameter name="group">group</parameter>
	</chsession>
</channel>

</appia>

=== aparra/appia/config/jgcs/open_group/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
         "http://appia.di.fc.ul.pt/xml/3.2/appiaxml.dtd">

<appia>

<template name="tcp_total">
	<session name="TCPSession" sharing="global">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.remote.RemoteGossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="total" sharing="private">
		<protocol>net.sf.appia.protocols.total.sequencer.TotalSequencerLayer</protocol>
	</session>
	<session name="atsl" sharing="private">
		<protocol>net.sf.appia.jgcs.protocols.top.TOPLayer</protocol>
	</session>
</template>

<template name="tcp">
	<session name="TCPSession" sharing="global">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="atsl" sharing="private">
		<protocol>net.sf.appia.jgcs.protocols.top.SimpleTOPLayer</protocol>
	</session>
</template>

<channel name="rrpc_group" template="tcp_total" initialized="no">
	<memorymanagement size="40000000" up_threshold="15000000" down_threshold="7000000" />
	<chsession name="atsl">
		<parameter name="gossip_address">10.10.0.2:10000</parameter>
	</chsession>
</channel>

<channel name="rrpc" template="tcp" initialized="no">
	<memorymanagement size="40000000" up_threshold="15000000" down_threshold="7000000" />
	<chsession name="atsl">
	</chsession>
</channel>

</appia>

=== aparra/appia/config/demo/perf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"../xml/appiaxml.dtd">
<appia>
	<template name="Perf Udp+Fifo Template">
	<session name="udp" sharing="private">
		<protocol>net.sf.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="fifo" sharing="private">
		<protocol>net.sf.appia.protocols.fifo.FifoLayer</protocol>
	</session>
	<session name="frag" sharing="private">
		<protocol>net.sf.appia.protocols.frag.FragLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>net.sf.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Udp+NakFifo Template">
	<session name="udp" sharing="private">
		<protocol>net.sf.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="nakfifo" sharing="private">
		<protocol>net.sf.appia.protocols.nakfifo.NakFifoLayer</protocol>
	</session>
	<session name="frag" sharing="private">
		<protocol>net.sf.appia.protocols.frag.FragLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>net.sf.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Tcp Template">
	<session name="tcp" sharing="private">
		<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>net.sf.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Udp+NakFifoMulticast Template">
	<session name="udp" sharing="private">
		<protocol>net.sf.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="nakfifo" sharing="private">
		<protocol>net.sf.appia.protocols.nakfifo.multicast.NakFifoMulticastLayer</protocol>
	</session>
	<session name="frag" sharing="private">
		<protocol>net.sf.appia.protocols.frag.FragLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>net.sf.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Tcp token Template">
	<session name="tcp" sharing="private">
		<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
    <session name="total" sharing="private">
		 <protocol>net.sf.appia.protocols.total.token.TotalTokenLayer</protocol>
    </session>	
	<session name="perf" sharing="private">
		<protocol>net.sf.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<management />


	<channel name="Perf Channel" template="Perf Udp+NakFifoMulticast Template" initialized="no">
		<chsession name="perf">
			<!-- Example for ring test with two members and IP-Multicast address for gossip dissemination. -->
			<parameter name="n">3</parameter>
			<parameter name="k">10</parameter>
			<parameter name="r">10</parameter>
			<parameter name="m">10</parameter>
			<parameter name="gossip">224.0.0.3:10001</parameter>
		</chsession>
	</channel>


	<channel name="Perf Channel" template="Perf Tcp Template" initialized="yes" managed="yes">
		<chsession name="perf">
			<parameter name="lo">false</parameter>
			<parameter name="n">2</parameter>
			<parameter name="k">10</parameter>
			<parameter name="r">10000</parameter>
			<parameter name="m">1000</parameter>
			<parameter name="gossip">224.0.0.3:10001</parameter>
		</chsession>
    <chsession name="total">
		<parameter name="num_messages_per_token">10</parameter>
	</chsession>
	</channel>

	<channel name="Perf Channel" template="Perf Udp+Fifo Template" initialized="no">
		<chsession name="perf">
			<parameter name="lo">true</parameter>
			<parameter name="n">4</parameter>
			<parameter name="k">1</parameter>
			<parameter name="r">10</parameter>
			<parameter name="m">1</parameter>
			<parameter name="gossip">224.0.0.3:10001</parameter>
		</chsession>
	</channel>

</appia>

=== aparra/appia/config/demo/perf_ssl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"http://appia.di.fc.ul.pt/xml/3.2.1/appiaxml.dtd">

<appia>

<template name="Perf SSL Template">
	<session name="ssl" sharing="private">
		<protocol>net.sf.appia.protocols.sslcomplete.SslCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>net.sf.appia.test.perf.PerfLayer</protocol>
	</session>
</template>

	<channel name="Perf Channel" template="Perf SSL Template" initialized="yes">
		<chsession name="perf">
			<!-- Example for ring test with two members and IP-Multicast address for gossip dissemination. -->
			<parameter name="n">2</parameter>
			<parameter name="k">100</parameter>
			<parameter name="r">10</parameter>
			<parameter name="m">100</parameter>
			<parameter name="gossip">224.0.0.3:10001</parameter>
		</chsession>
		
		<chsession name="ssl">
        	<parameter name="protocol">SSL</parameter>
        	<parameter name="keystore_file">/tmp/appia.keystore</parameter>
        	<parameter name="passphrase">pass</parameter>
		</chsession>
	</channel>

</appia>

=== aparra/appia/config/demo/messenger.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"http://appia.di.fc.ul.pt/xml/3.2.1/appiaxml.dtd">
<appia>
<template name="text">
	<session name="tcp" sharing="global">
		<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="label">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="label">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="label">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="label">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="label">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="label">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="label">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="label">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="label">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="msg" sharing="label">
		<protocol>net.sf.appia.test.xml.MessengerLayer</protocol>
	</session>
</template>
<template name="draw">
	<session name="tcp" sharing="global">
		<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
		<session name="gbl" sharing="label">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="label">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="label">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="label">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="label">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="label">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="label">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="label">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="label">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="msg" sharing="label">
		<protocol>net.sf.appia.test.xml.MessengerLayer</protocol>
	</session>
</template>
</appia>

=== aparra/appia/config/jgcs/appia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
         "appiaxml.dtd">
 

<appia>

<template name="tcp_vsc">
	<session name="tcp" sharing="global">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="global">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="global">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="global">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>
	<session name="intral" sharing="global">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="global">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="global">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="global">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="global">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="global">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="loopback" sharing="private">
		<protocol>net.sf.appia.protocols.loopBack.LoopBackLayer</protocol>
	</session>
	<session name="atsl" sharing="global">
		<protocol>net.sf.appia.jgcs.protocols.top.TOPLayer</protocol>
	</session>
</template>

<template name="tcp_total">
	<session name="tcp" sharing="global">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="global">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="global">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="global">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>
	<session name="intral" sharing="global">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="global">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="global">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="global">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="global">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="global">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="total" sharing="private">
		<protocol>org.continuent.appia.protocols.total.sequencer.TotalSequencerLayer</protocol>
	</session>	<session name="atsl" sharing="global">
		<protocol>net.sf.appia.jgcs.protocols.top.TOPLayer</protocol>
	</session>
</template>

<channel name="vsc+fifo" template="tcp_vsc" initialized="no">
	<memorymanagement size="100000000" up_threshold="60000000" down_threshold="30000000" />
	<chsession name="atsl">
		<parameter name="gossip_address">224.1.1.7</parameter>
	</chsession>
</channel>

<channel name="vsc+total" template="tcp_total" initialized="no">
	<memorymanagement size="100000000" up_threshold="60000000" down_threshold="30000000" />
	<chsession name="atsl">
		<parameter name="gossip_address">224.1.1.7</parameter>
	</chsession>
</channel>

</appia>

=== aparra/appia/config/gossipServer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"http://appia.di.fc.ul.pt/xml/3.2.1/appiaxml.dtd">
<appia>
	<template name="Gossip Group Template">
	<session name="udp" sharing="private">
		<protocol>net.sf.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="fifo" sharing="private">
		<protocol>net.sf.appia.protocols.fifo.FifoLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>net.sf.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>net.sf.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>net.sf.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>net.sf.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>net.sf.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>net.sf.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>net.sf.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>net.sf.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="gossip" sharing="label">
		<protocol>net.sf.appia.protocols.gossipServer.GossipServerLayer</protocol>
	</session>
	</template>

	<template name="Gossip Client Template">
	<session name="udp" sharing="private">
		<protocol>net.sf.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="fifo" sharing="private">
		<protocol>net.sf.appia.protocols.fifo.FifoLayer</protocol>
	</session>
	<session name="gossip" sharing="label">
		<protocol>net.sf.appia.protocols.gossipServer.GossipServerLayer</protocol>
	</session>
	</template>

	<channel name="Gossip Channel" template="Gossip Client Template" initialized="yes" label="Gossip Shared">
		<chsession name="gossip">
			<!-- DEFAULTS
			<parameter name="port">10000</parameter>
			<parameter name="remove_time">20000</parameter>
			<parameter name="timer">1000</parameter>
			<parameter name="debug">false</parameter>
			<parameter name="gossip">localhost:10000</parameter>
			-->
		</chsession>
	</channel>

	<channel name="Gossip Group Channel" template="Gossip Group Template" initialized="yes" label="Gossip Shared"/>
</appia>

=== aparra/appia/config/jgcs/open_group/appia-client.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
         "../../xml/appiaxml.dtd">

<appia>

<template name="tcp">
	<session name="TCPSession" sharing="private">
		<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="remoteview" sharing="private">
		<protocol>net.sf.appia.protocols.group.remote.RemoteViewLayer</protocol>
	</session>
	<session name="remoteaddr" sharing="private">
		<protocol>net.sf.appia.jgcs.protocols.remote.RemoteAddressLayer</protocol>
	</session>
	<session name="atsl" sharing="private">
		<protocol>net.sf.appia.jgcs.protocols.top.SimpleTOPLayer</protocol>
	</session>
</template>

<management local="yes" />

<channel name="rrpc" template="tcp" initialized="no" managed="yes">
	<!-- <memorymanagement size="80000000" up_threshold="30000000" down_threshold="14000000" /> -->
	<chsession name="remoteview">
		<parameter name="gossip">10.0.1.2:10000</parameter>
	</chsession>
	<chsession name="remoteaddr">
		<parameter name="group">group</parameter>
	</chsession>
</channel>

</appia>
